# Generated by Django 4.2.5 on 2023-09-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliumApp', '0002_alter_prices_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement_name', models.CharField(max_length=250)),
                ('zip_code', models.IntegerField()),
                ('price_m2', models.IntegerField()),
                ('meteo', models.IntegerField(blank=True, default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
    ]
