# Generated by Django 4.2.5 on 2023-09-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliumApp', '0003_departement_delete_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='meteo',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
