# Generated by Django 4.2.5 on 2023-09-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foliumApp", "0005_alter_departement_price_m2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departement",
            name="meteo",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
