# Generated by Django 4.2.5 on 2023-09-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliumApp', '0006_alter_departement_meteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
