# Generated by Django 4.2.5 on 2023-09-27 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foliumApp", "0007_alter_departement_zip_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=50)),
                ("duration", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("price", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="foliumApp.action",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.CharField(max_length=50)),
                (
                    "departement_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="foliumApp.departement",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="foliumApp.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngredientQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.CharField(max_length=50)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="foliumApp.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("area", models.CharField(max_length=50)),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="foliumApp.departement",
                    ),
                ),
                ("machines", models.ManyToManyField(to="foliumApp.machine")),
                ("recipes", models.ManyToManyField(to="foliumApp.recipe")),
                ("stocks", models.ManyToManyField(to="foliumApp.ingredientquantity")),
            ],
        ),
        migrations.AddField(
            model_name="action",
            name="ingredient",
            field=models.ManyToManyField(to="foliumApp.ingredientquantity"),
        ),
        migrations.AddField(
            model_name="action",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="foliumApp.machine"
            ),
        ),
    ]
