# Generated by Django 4.2.5 on 2023-09-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foliumApp", "0009_rename_departement_name_departement_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="departement",
            name="langitude",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="departement",
            name="latitude",
            field=models.IntegerField(default=0),
        ),
    ]
