# Generated by Django 4.2.5 on 2023-09-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foliumApp", "0011_rename_langitude_departement_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departement",
            name="latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="departement",
            name="longitude",
            field=models.FloatField(default=0),
        ),
    ]
