# Generated by Django 4.2.5 on 2023-09-30 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foliumApp", "0012_alter_departement_latitude_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departement",
            options={"ordering": ["zip_code"]},
        ),
        migrations.AlterModelOptions(
            name="factory",
            options={"verbose_name_plural": "factories"},
        ),
    ]
